### PR TITLE
Create MATRIXCALUCULATOR.c

### PR DESCRIPTION
**Pull request by Ashiiidev**
please accept my pr and merge it

### CODE REVIEW

**Comment by Edwinliby** [comment]
> please accept my pr and merge it

There is some error fix it.

**Comment by Ashiiidev** [comment]
This is the wright code

**Comment by Ashiiidev** [comment]
This si the final code if you like it you can merge it

**Comment by Ashiiidev** [comment]
I closing my pull request
Thanks for your help

**Comment by Ashiiidev** [comment]
Because I did it by mistake

**Comment by Ashiiidev** [comment]
Sorry for my inconvenience

**Pull request closed without merging**
